In [1]:
import numpy as np


# 1. Array Creation

In [2]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [3]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
print((np.eye(3,3)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [6]:
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [7]:
print(np.random.rand(3,2))

[[0.7911287  0.24733331]
 [0.07197235 0.91882964]
 [0.39462386 0.76101665]]


# 2. Array Inspection

In [8]:
print(arr.shape)

(2, 3)


In [9]:
arr.dtype

dtype('int32')

In [10]:
arr.ndim

2

In [11]:
arr.size


6

# 3. Indexing & Slicing

In [12]:
arr[0]

array([1, 2, 3])

In [13]:
arr[1:3]
#row 1 and 2 are returned
#last one is not inclusive

array([[4, 5, 6]])

In [14]:
arr[:,1]

array([2, 5])

In [15]:
#arr[arr>4]

# 4. Mathematical Operations

In [16]:
arr+10

array([[11, 12, 13],
       [14, 15, 16]])

In [17]:
np.mean(arr)


3.5

In [18]:
np.std(arr)

1.707825127659933

In [19]:
np.var(arr)

2.9166666666666665

In [20]:
np.sum(arr)

21

In [21]:
np.diff(arr)

array([[1, 1],
       [1, 1]])

In [22]:
np.cumsum(arr)

array([ 1,  3,  6, 10, 15, 21])

In [23]:
np.cumsum(arr,axis=0) 
#axis=0 : column-wise sum

array([[1, 2, 3],
       [5, 7, 9]])

In [24]:
np.cumsum(arr,axis=1) 

array([[ 1,  3,  6],
       [ 4,  9, 15]])

# 5.Reshaping & Combining

In [25]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
arr.flatten()

array([1, 2, 3, 4, 5, 6])

In [27]:
arr1=([[6,7,8],[9,10,12]])

In [28]:
np.vstack((arr, arr1))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 12]])

In [29]:
np.hstack((arr, arr1))

array([[ 1,  2,  3,  6,  7,  8],
       [ 4,  5,  6,  9, 10, 12]])

# 6.Missing Values & NaNs

In [ ]:
#Nans : Not a Number

In [30]:
np.isnan(arr)

array([[False, False, False],
       [False, False, False]])

In [31]:
np.nanmean(arr) 

3.5

In [32]:
arr2=([1,4,5, np.nan])

In [33]:
np.nan_to_num(arr2) 

array([1., 4., 5., 0.])